version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres